name: Trader
description: Probleme / Ideen / Wünsche
title: "[Title]"
labels: []
projects: ["impuls-energy/36"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Idee / Wunsch
      description: Beschreibe deine Idee in 1-2 Sätzen
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Service Description
      description: Please describe the service functionality in 2-3 sentences.
    validations:
      required: true   
