name: Trader
description: Probleme / Ideen / Wünsche
title: "[Title]"
labels: []
projects: ["impuls-energy/36"]
body:
  - type: input
    id: link
    attributes:
      label: Repository Link
      description: Please copy the link of the repository here.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Service Description
      description: Please describe the service functionality in 2-3 sentences.
    validations:
      required: true   
